CREATE TABLE IF NOT EXISTS Users(
	User_ID INTEGER NOT NULL AUTO_INCREMENT,
	Username varchar(20) NOT NULL UNIQUE,
	Password  varchar(256) NOT NULL,
	PRIMARY KEY (User_ID)
)character set = utf8;

CREATE TABLE IF NOT EXISTS Papers(
	Paper_ID INTEGER NOT NULL AUTO_INCREMENT,
	Title VARCHAR(200) NOT NULL,
	Address VARCHAR(100) NOT NULL, 
	GitHub VARCHAR(100),
	Abstract VARCHAR(2000) NOT NULL,
	Stars int,
	Authors VARCHAR(200) NOT NULL,
	Pulish_time TIMESTAMP NOT NULL, 
	PRIMARY KEY (Paper_ID)
)character set = utf8;


CREATE TABLE IF NOT EXISTS Subjects(
	Subject_ID INTEGER NOT NULL AUTO_INCREMENT,
	Tag VARCHAR(50) NOT NULL UNIQUE,
	Name VARCHAR(200) NOT NULL UNIQUE,
	PRIMARY KEY (Subject_ID)
)character set = utf8;

CREATE TABLE IF NOT EXISTS Comments(
	Comment_ID INTEGER NOT NULL AUTO_INCREMENT,
	Commenter_ID INTEGER NOT NULL,
	Paper_ID INTEGER NOT NULL,
	Content VARCHAR(1000) NOT NULL,
	Comment_time DATETIME NOT NULL, 
	Father_comment_ID INTEGER,
	FOREIGN KEY (Commenter_ID) REFERENCES Users(USER_ID),
	FOREIGN KEY (Paper_ID) REFERENCES Papers(Paper_ID),
	FOREIGN KEY (Father_comment_ID) REFERENCES Comments(Comment_ID),
	PRIMARY KEY (Comment_ID)
)character set = utf8;


CREATE TABLE IF NOT EXISTS Archives(
	USER_ID INTEGER,
	Paper_ID INTEGER,
	Archive_time DATETIME NOT NULL, 
	FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID)
	ON DELETE CASCADE,
	FOREIGN KEY (Paper_ID) REFERENCES Papers(Paper_ID)
	ON DELETE CASCADE,
	PRIMARY KEY (USER_ID,Paper_ID)
)character set = utf8;

-- 因为PRIMARY KEY，所以unique
CREATE TABLE IF NOT EXISTS Like_Paper(
	USER_ID INTEGER,
	Paper_ID INTEGER,
	Like_time DATETIME NOT NULL, 
	FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID)
	ON DELETE CASCADE,
	FOREIGN KEY (Paper_ID) REFERENCES Papers(Paper_ID)
	ON DELETE CASCADE,
	PRIMARY KEY (USER_ID,Paper_ID)
)character set = utf8;

-- 因为PRIMARY KEY，所以unique
CREATE TABLE IF NOT EXISTS Like_Comment(
	USER_ID INTEGER,
	Comment_ID INTEGER,
	Like_time DATETIME NOT NULL, 
	FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID)
	ON DELETE CASCADE,
	FOREIGN KEY (Comment_ID) REFERENCES Comments(Comment_ID)
	ON DELETE CASCADE,
	PRIMARY KEY (USER_ID,Comment_ID)
)character set = utf8;

-- 因为PRIMARY KEY，所以unique
CREATE TABLE IF NOT EXISTS Follow(
	USER_ID INTEGER,
	Subject_ID INTEGER,
	FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID)
	ON DELETE CASCADE,
	FOREIGN KEY (Subject_ID) REFERENCES Subjects(Subject_ID)
	ON DELETE CASCADE,
	PRIMARY KEY (USER_ID,Subject_ID)
)character set = utf8;

-- 因为PRIMARY KEY，所以unique
CREATE TABLE IF NOT EXISTS In_Subject(
	Paper_ID INTEGER,
	Subject_ID INTEGER,
	FOREIGN KEY (Paper_ID) REFERENCES Papers(Paper_ID)
	ON DELETE CASCADE,
	FOREIGN KEY (Subject_ID) REFERENCES Subjects(Subject_ID)
	ON DELETE CASCADE,
	PRIMARY KEY (Paper_ID,Subject_ID)
)character set = utf8;

